name: cypress master CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

- name: Send mailer
  # You may pin to the exact commit or the version.
  # uses: devellany/send-mail@45dbe31722b9c29635bc9d60315d420218093c56
  uses: devellany/send-mail@v1.0.2
  with:
    # Enter SMTP host.
    host: smtp.gmail.com
    # Enter SMTP port. (defaults to 465)
    port: # optional, default is 465
    # Enter SMTP host account.
    account: himanshu.test3212@gmail.com
    # Enter SMTP host account password.
    password: pxkekvoejugxoxsb
    # Enter sender name.
    sender: himanshu
    # Enter sender mail.
    from: himanshu.test3212@gmail.com
    # Enter recipient emails and separated with 'comma'. (The prefix 'file://' if you want to read a file)
    to: himanshu.shrivastav@absolutdata.com
    # Enter the subject of the mail. (The prefix 'file://' if you want to read a file)
    subject: test mail
    # Enter the body of the mail. (The prefix 'file://' if you want to read a file)
    body: test body
    # Enter Content-Type HTTP header. (defaults to 'text/plain')
    contentType: # optional, default is text/plain
    # Attachment files are entered as an array. Required key 'path'. (The prefix 'file://' if you want to read a file)
    attachments: # optional
