name: cypress master CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.x
          - 14.x
          - 16.x
  steps:
    uses: actions/setup-node@v2
    name: 'Use Node.js ${{ matrix.node-version }}'
    with:
      server_address: smtp.gmail.com
      server_port: 465
      username: himanshu.test3212@gmail.com
      password: pssuqzovfzxepnqa
      subject: Github Actions job result
      to: himanshu.shrivastav@absolutdata.com, gagan, gagandeep.singh@absolutdata.com
      from: Luke Skywalker
      secure: true
      body: 'Build job of ${{github.repository}} completed successfully!'
      html_body: 'file://README.html'
      reply_to: luke@example.com
      in_reply_to: <random-luke@example.com>
      ignore_cert: true
      convert_markdown: true
      priority: low
